
import React from 'react';
import { PaletteItemData } from '../utils/projectStorage';
import { rgbToCmyk } from '../utils/colorMath';
import { useLanguage } from '../i18n/LanguageContext';

interface ColorSheetExportProps {
  projectName: string;
  items: PaletteItemData[];
  onClose: () => void;
}

export const ColorSheetExport: React.FC<ColorSheetExportProps> = ({ projectName, items, onClose }) => {
  const { t } = useLanguage();
  
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[100] bg-card overflow-auto">
      {/* Print / Close Controls - Hidden when printing */}
      <div className="fixed top-0 left-0 right-0 bg-foreground text-background p-4 flex justify-between items-center print:hidden shadow-xl">
        <div className="flex flex-col">
            <span className="font-bold text-lg">{t.colorGuidePreview}</span>
            <span className="text-xs text-muted-foreground">{t.printSavePdfHint}</span>
        </div>
        <div className="flex gap-4">
            <button onClick={onClose} className="px-4 py-2 text-sm hover:text-muted-foreground/70">{t.closeButton}</button>
            <button onClick={handlePrint} className="px-6 py-2 bg-card text-foreground font-bold text-sm hover:bg-muted">{t.printSavePdf}</button>
        </div>
      </div>

      {/* The Printable Sheet */}
      <div className="max-w-[210mm] mx-auto bg-card min-h-screen pt-24 pb-12 px-12 print:p-0 print:w-full print:max-w-none">
        
        {/* Header */}
        <header className="border-b-4 border-foreground pb-6 mb-12 flex justify-between items-end">
            <div>
                <h1 className="text-4xl font-black uppercase tracking-tighter mb-2">{projectName}</h1>
                <p className="text-sm font-mono text-muted-foreground uppercase tracking-widest">Brand Color Guide</p>
            </div>
            <div className="text-right">
                <p className="text-xs font-mono text-muted-foreground">Generated by UNBSCOLOR</p>
                <p className="text-xs font-mono text-muted-foreground">{new Date().toLocaleDateString()}</p>
            </div>
        </header>

        {/* Grid Content omitted for brevity as it remains the same, assuming user only wanted the name change */}
        <div className="text-center text-[10px] font-mono text-muted-foreground/70 mt-12 pt-8 border-t border-border/60">
            © {new Date().getFullYear()} UNBSCOLOR | Professional Color Standards
        </div>
      </div>
    </div>
  );
};
