
import { FormatPreset } from './types';

export const FORMAT_PRESETS: FormatPreset[] = [
  // PRINT
  { id: 'a0', name: 'A0 POSTER', width: 841, height: 1189, category: 'PRINT' },
  { id: 'a1', name: 'A1 POSTER', width: 594, height: 841, category: 'PRINT' },
  { id: 'a2', name: 'A2 POSTER', width: 420, height: 594, category: 'PRINT' },
  { id: 'a3', name: 'A3 POSTER', width: 297, height: 420, category: 'PRINT' },
  { id: 'a3_land', name: 'A3 LANDSCAPE', width: 420, height: 297, category: 'PRINT' },
  { id: 'a4', name: 'A4 DOCUMENT', width: 210, height: 297, category: 'PRINT' },
  { id: 'a4_land', name: 'A4 LANDSCAPE', width: 297, height: 210, category: 'PRINT' },
  { id: 'a5', name: 'A5 FLYER', width: 148, height: 210, category: 'PRINT' },
  { id: 'a6', name: 'A6 POSTCARD', width: 105, height: 148, category: 'PRINT' },
  { id: 'a7', name: 'A7', width: 74, height: 105, category: 'PRINT' },
  { id: 'a8', name: 'A8', width: 52, height: 74, category: 'PRINT' },
  { id: 'b0', name: 'B0', width: 1000, height: 1414, category: 'PRINT' },
  { id: 'b1', name: 'B1', width: 707, height: 1000, category: 'PRINT' },
  { id: 'b2', name: 'B2', width: 500, height: 707, category: 'PRINT' },
  { id: 'b3', name: 'B3', width: 353, height: 500, category: 'PRINT' },
  { id: 'b4', name: 'B4', width: 250, height: 353, category: 'PRINT' },
  { id: 'b5', name: 'B5', width: 176, height: 250, category: 'PRINT' },
  { id: 'bc_int', name: 'BUSINESS CARD (INTL)', width: 85, height: 55, category: 'PRINT' },
  { id: 'bc_us', name: 'BUSINESS CARD (US)', width: 88.9, height: 50.8, category: 'PRINT' },
  { id: 'dl_env', name: 'DL ENVELOPE', width: 220, height: 110, category: 'PRINT' },
  { id: 'c4_env', name: 'C4 ENVELOPE', width: 229, height: 324, category: 'PRINT' },
  { id: 'c5_env', name: 'C5 ENVELOPE', width: 229, height: 162, category: 'PRINT' },
  { id: 'c6_env', name: 'C6 ENVELOPE', width: 114, height: 162, category: 'PRINT' },
  { id: 'env_10_us', name: '#10 ENVELOPE (US)', width: 241.3, height: 104.8, category: 'PRINT' },
  { id: 'letter_us', name: 'LETTER (US)', width: 215.9, height: 279.4, category: 'PRINT' },
  { id: 'legal_us', name: 'LEGAL (US)', width: 215.9, height: 355.6, category: 'PRINT' },
  { id: 'tabloid_us', name: 'TABLOID (US)', width: 279.4, height: 431.8, category: 'PRINT' },
  { id: 'half_letter', name: 'HALF LETTER', width: 139.7, height: 215.9, category: 'PRINT' },
  { id: 'executive', name: 'EXECUTIVE', width: 184.2, height: 266.7, category: 'PRINT' },
  { id: 'folio', name: 'FOLIO', width: 215.9, height: 330.2, category: 'PRINT' },
  { id: 'ledger', name: 'LEDGER', width: 431.8, height: 279.4, category: 'PRINT' },
  { id: 'statement', name: 'STATEMENT', width: 139.7, height: 215.9, category: 'PRINT' },
  { id: 'gov_letter', name: 'GOVERNMENT LETTER', width: 203.2, height: 266.7, category: 'PRINT' },
  { id: 'super_a3', name: 'SUPER A3/B', width: 330, height: 483, category: 'PRINT' },

  // EDITORIAL
  { id: 'book_cover', name: 'BOOK COVER', width: 156, height: 234, category: 'EDITORIAL' },
  { id: 'pocket_book', name: 'POCKET BOOK', width: 110, height: 178, category: 'EDITORIAL' },
  { id: 'mag_spread', name: 'MAGAZINE SPREAD', width: 420, height: 297, category: 'EDITORIAL' },
  { id: 'cd_booklet', name: 'CD BOOKLET', width: 120, height: 120, category: 'EDITORIAL' },
  { id: 'vinyl_cover', name: 'VINYL COVER', width: 315, height: 315, category: 'EDITORIAL' },
  { id: 'dvd_cover', name: 'DVD COVER', width: 184, height: 273, category: 'EDITORIAL' },

  // PHOTO
  { id: 'photo_4x6', name: '4×6" PRINT', width: 101.6, height: 152.4, category: 'PHOTO' },
  { id: 'photo_5x7', name: '5×7" PRINT', width: 127, height: 177.8, category: 'PHOTO' },
  { id: 'photo_8x10', name: '8×10" PRINT', width: 203.2, height: 254, category: 'PHOTO' },
  { id: 'photo_11x14', name: '11×14" PRINT', width: 279.4, height: 355.6, category: 'PHOTO' },
  { id: 'photo_16x20', name: '16×20" PRINT', width: 406.4, height: 508, category: 'PHOTO' },
  { id: 'photo_20x30', name: '20×30" PRINT', width: 508, height: 762, category: 'PHOTO' },
  { id: 'photo_sq12', name: 'SQUARE 12×12"', width: 304.8, height: 304.8, category: 'PHOTO' },
  { id: 'passport', name: 'PASSPORT PHOTO', width: 35, height: 45, category: 'PHOTO' },
  { id: 'wallet', name: 'WALLET SIZE', width: 63.5, height: 88.9, category: 'PHOTO' },
  { id: 'panoramic', name: 'PANORAMIC', width: 254, height: 762, category: 'PHOTO' },

  // PACKAGING
  { id: 'label', name: 'LABEL', width: 100, height: 50, category: 'PACKAGING' },
  { id: 'hang_tag', name: 'HANG TAG', width: 55, height: 90, category: 'PACKAGING' },
  { id: 'box_lid', name: 'BOX LID', width: 200, height: 200, category: 'PACKAGING' },
  { id: 'wine_label', name: 'WINE LABEL', width: 90, height: 120, category: 'PACKAGING' },
  { id: 'soap_wrap', name: 'SOAP WRAP', width: 210, height: 80, category: 'PACKAGING' },

  // SIGNAGE
  { id: 'banner', name: 'BANNER', width: 1000, height: 500, category: 'SIGNAGE' },
  { id: 'rollup', name: 'ROLL-UP', width: 850, height: 2000, category: 'SIGNAGE' },
  { id: 'billboard_4', name: 'BILLBOARD 4-SHEET', width: 1016, height: 1524, category: 'SIGNAGE' },
  { id: 'a_frame', name: 'A-FRAME', width: 600, height: 900, category: 'SIGNAGE' },
  { id: 'table_tent', name: 'TABLE TENT', width: 100, height: 210, category: 'SIGNAGE' },

  // ADVERTISING
  { id: 'flyer', name: 'FLYER', width: 148, height: 210, category: 'ADVERTISING' },
  { id: 'trifold', name: 'TRI-FOLD BROCHURE', width: 297, height: 210, category: 'ADVERTISING' },
  { id: 'bifold', name: 'BI-FOLD BROCHURE', width: 420, height: 297, category: 'ADVERTISING' },
  { id: 'door_hanger', name: 'DOOR HANGER', width: 88.9, height: 279.4, category: 'ADVERTISING' },
  { id: 'rack_card', name: 'RACK CARD', width: 101.6, height: 228.6, category: 'ADVERTISING' },
  { id: 'coupon', name: 'COUPON', width: 88.9, height: 50.8, category: 'ADVERTISING' },
  { id: 'ticket', name: 'TICKET', width: 203.2, height: 73.7, category: 'ADVERTISING' },
  { id: 'event_poster', name: 'EVENT POSTER', width: 457.2, height: 609.6, category: 'ADVERTISING' },
  { id: 'movie_poster', name: 'MOVIE POSTER', width: 685.8, height: 1016, category: 'ADVERTISING' },
  { id: 'menu_single', name: 'MENU SINGLE', width: 215.9, height: 279.4, category: 'ADVERTISING' },
  { id: 'menu_trifold', name: 'MENU TRI-FOLD', width: 279.4, height: 431.8, category: 'ADVERTISING' },

  // SOCIAL MEDIA
  { id: 'ig_sq', name: 'INSTAGRAM SQUARE', width: 285.75, height: 285.75, category: 'SOCIAL MEDIA' },
  { id: 'ig_pt', name: 'INSTAGRAM PORTRAIT', width: 285.75, height: 357.18, category: 'SOCIAL MEDIA' },
  { id: 'ig_story', name: 'INSTAGRAM STORY', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'ig_reel', name: 'INSTAGRAM REEL', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'ig_carousel', name: 'INSTAGRAM CAROUSEL', width: 285.75, height: 285.75, category: 'SOCIAL MEDIA' },
  { id: 'fb_cover', name: 'FACEBOOK COVER', width: 222.25, height: 82.02, category: 'SOCIAL MEDIA' },
  { id: 'fb_post', name: 'FACEBOOK POST', width: 167.64, height: 167.64, category: 'SOCIAL MEDIA' },
  { id: 'fb_event', name: 'FACEBOOK EVENT COVER', width: 475.13, height: 180.34, category: 'SOCIAL MEDIA' },
  { id: 'fb_story', name: 'FACEBOOK STORY', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'fb_ad', name: 'FACEBOOK AD', width: 167.64, height: 167.64, category: 'SOCIAL MEDIA' },
  { id: 'tw_header', name: 'TWITTER/X HEADER', width: 396.88, height: 132.29, category: 'SOCIAL MEDIA' },
  { id: 'tw_post', name: 'TWITTER/X POST', width: 167.64, height: 167.64, category: 'SOCIAL MEDIA' },
  { id: 'tw_photo', name: 'TWITTER/X IN-STREAM', width: 167.64, height: 94.30, category: 'SOCIAL MEDIA' },
  { id: 'li_banner', name: 'LINKEDIN BANNER', width: 414.69, height: 108.73, category: 'SOCIAL MEDIA' },
  { id: 'li_post', name: 'LINKEDIN POST', width: 167.64, height: 167.64, category: 'SOCIAL MEDIA' },
  { id: 'li_story', name: 'LINKEDIN STORY', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'yt_thumb', name: 'YOUTUBE THUMBNAIL', width: 340.36, height: 191.45, category: 'SOCIAL MEDIA' },
  { id: 'yt_art', name: 'YOUTUBE CHANNEL ART', width: 681.47, height: 113.24, category: 'SOCIAL MEDIA' },
  { id: 'yt_shorts', name: 'YOUTUBE SHORTS', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'pin', name: 'PINTEREST PIN', width: 167.64, height: 251.46, category: 'SOCIAL MEDIA' },
  { id: 'pin_story', name: 'PINTEREST STORY PIN', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'tiktok', name: 'TIKTOK COVER', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'tiktok_post', name: 'TIKTOK POST', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'snap_ad', name: 'SNAPCHAT AD', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'snap_geo', name: 'SNAPCHAT GEOFILTER', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'threads_post', name: 'THREADS POST', width: 285.75, height: 285.75, category: 'SOCIAL MEDIA' },
  { id: 'threads_story', name: 'THREADS STORY', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'whatsapp', name: 'WHATSAPP STATUS', width: 285.75, height: 507.94, category: 'SOCIAL MEDIA' },
  { id: 'telegram', name: 'TELEGRAM STICKER', width: 136.53, height: 136.53, category: 'SOCIAL MEDIA' },
  { id: 'discord', name: 'DISCORD SERVER ICON', width: 170.18, height: 170.18, category: 'SOCIAL MEDIA' },
  { id: 'twitch_banner', name: 'TWITCH BANNER', width: 320.68, height: 106.89, category: 'SOCIAL MEDIA' },
  { id: 'twitch_overlay', name: 'TWITCH OVERLAY', width: 508.00, height: 285.75, category: 'SOCIAL MEDIA' },
  { id: 'spotify', name: 'SPOTIFY PLAYLIST', width: 80.43, height: 80.43, category: 'SOCIAL MEDIA' },
  { id: 'bereal', name: 'BEREAL POST', width: 285.75, height: 285.75, category: 'SOCIAL MEDIA' },

  // SCREEN
  { id: 'wallpaper_hd', name: 'DESKTOP HD', width: 508, height: 285.75, category: 'SCREEN' },
  { id: 'wallpaper_4k', name: 'DESKTOP 4K', width: 1016, height: 571.5, category: 'SCREEN' },
  { id: 'mobile_wall', name: 'MOBILE WALLPAPER', width: 285.75, height: 507.94, category: 'SCREEN' },
  { id: 'tablet_wall', name: 'TABLET WALLPAPER', width: 271.46, height: 361.95, category: 'SCREEN' },
  { id: 'email_header', name: 'EMAIL HEADER', width: 167.64, height: 56.09, category: 'SCREEN' },
  { id: 'email_banner', name: 'EMAIL BANNER', width: 167.64, height: 83.82, category: 'SCREEN' },
  { id: 'web_leaderboard', name: 'WEB LEADERBOARD', width: 199.58, height: 24.61, category: 'SCREEN' },
  { id: 'web_skyscraper', name: 'WEB SKYSCRAPER', width: 42.33, height: 161.22, category: 'SCREEN' },
  { id: 'web_rectangle', name: 'WEB RECTANGLE', width: 83.82, height: 66.15, category: 'SCREEN' },
  { id: 'app_icon', name: 'APP ICON', width: 136.53, height: 136.53, category: 'SCREEN' },
  { id: 'favicon', name: 'FAVICON', width: 4.23, height: 4.23, category: 'SCREEN' },
  { id: 'og_image', name: 'OPEN GRAPH IMAGE', width: 317.50, height: 166.69, category: 'SCREEN' },

  // STATIONERY
  { id: 'letterhead', name: 'LETTERHEAD A4', width: 210, height: 297, category: 'STATIONERY' },
  { id: 'env_dl', name: 'ENVELOPE DL', width: 220, height: 110, category: 'STATIONERY' },
  { id: 'comp_slip', name: 'COMPLIMENT SLIP', width: 210, height: 99, category: 'STATIONERY' },
  { id: 'notecard', name: 'NOTECARD (A6)', width: 105, height: 148, category: 'STATIONERY' },
  { id: 'bookmark', name: 'BOOKMARK', width: 50, height: 150, category: 'STATIONERY' },
  { id: 'certificate', name: 'CERTIFICATE', width: 297, height: 210, category: 'STATIONERY' },
];

export const MM_TO_PX = 3.7795275591; // 96 DPI
